hourly_wage = input("Please enter your hourly wage: ")
print("Hourly wage: ")
print(hourly_wage)
print("Hours worked: ")
hours_worked = input("How many hours did you work this week? ")
print(hours_worked)
